RentACar/Models/Korisnik.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RentACar.Models
{
    public class Korisnik
    {
        public Guid KorisnikID { get; set; }
        public string Email { get; set; }
        public string Lozinka { get; set; }
    }
}

RentACar/Controllers/KorisnikController.cs
using RentACar.BLL;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace RentACar.Controllers
{
    public class KorisnikController : Controller
    {
        private KorisnikServis korisnikServis;

        public KorisnikController()
        {
            this.korisnikServis = new KorisnikServis();
        }

        
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Prikazuje formu za prijavu.
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult Prijava()
        {
            if (User.Identity.IsAuthenticated)
                return RedirectToAction("Dashboard", "Home");
            return View();
        }

        /// <summary>
        /// Prijavljuje korisnika na sistem.
        /// </summary>
        /// <param name="korisnik"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Prijava(Korisnik korisnik)
        {
            if(ModelState.IsValid)
            {
                if (IsValid(korisnik.Email, korisnik.Lozinka))
                {
                    FormsAuthentication.SetAuthCookie(korisnik.Email, false);
                    return RedirectToAction("Dashboard", "Home");
                }
                else
                    ModelState.AddModelError("", "Pogrešan email ili lozinka.");
            }
            return View(korisnik);
        }

        //public void Registracija()
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var crypto = new SimpleCrypto.PBKDF2();
        //        var cryptoLozinka = crypto.Compute("P@ssw0rd");

        //        var model = new DAL.Korisnik
        //        {
        //            Email = "crnic.nikola@gmail.com",
        //            Lozinka = cryptoLozinka,
        //            LozinkaSalt = crypto.Salt,
        //            KorisnikID = Guid.NewGuid()
        //        };

        //        korisnikServis.Sacuvaj(model);
        //    }
        //}

        /// <summary>
        /// Odjavljuje korisnika sa sistema.
        /// </summary>
        /// <returns></returns>
        public ActionResult Odjava()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }

        /// <summary>
        /// Provjerava da li su unešeni podaci za prijavu na sistem ispravni.
        /// </summary>
        /// <param name="Email"></param>
        /// <param name="Lozinka"></param>
        /// <returns></returns>
        public bool IsValid(string Email, string Lozinka)
        {
            bool isValid = false;

            var crypto = new SimpleCrypto.PBKDF2();

            var korisnik = korisnikServis.DohvatiKorisnika(Email);

            if(korisnik != null)
            {
                if (korisnik.Lozinka == crypto.Compute(Lozinka, korisnik.LozinkaSalt))
                    isValid = true;
            }

            return isValid;
        }
    }
}

RentACar/Views/Korisnik/Prijava.cshtml
@model RentACar.Models.Korisnik
@{
    ViewBag.Title = "Prijava";
}

<script type="text/javascript" src="~/Scripts/helpers.js"></script>
<script type="text/javascript">
    $(document).ready(function(){
        PorukeValidacija();

        $("#forma-prijava").validate({
            rules: {
                Email: {
                    required: true,
                    email: true
                },
                Lozinka: {
                    required: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
    
</script>
<div class="page-header"></div>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-4 col-md-offset-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <div class="panel-title"><h4 class="text-center">@ViewBag.Title</h4></div>
                </div>
                <div class="panel-body">
                    @using (Html.BeginForm("Prijava", "Korisnik", FormMethod.Post, new { @id = "forma-prijava" }))
                    {
                        <span class="error">@Html.ValidationSummary(true, "Prijava nije uspjela.")</span>
                        <fieldset>

                            <div class="form-group">
                                <label>Email</label>
                                @Html.TextBoxFor(u => u.Email, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Email, null, new { @class = "inline-help error" })
                            </div>

                            <div class="form-group">
                                <label>Lozinka</label>
                                @Html.TextBoxFor(u => u.Lozinka, new { @class = "form-control", @type = "password" })
                                @Html.ValidationMessageFor(u => u.Lozinka, null, new { @class = "inline-help error" })
                            </div>
                            <div class="form-group">
                                <input class="btn btn-primary" type="submit" value="Prijava" />
                                @Html.ActionLink("Odustani", "Index", "Home", null, new { @class = "btn btn-default" })
                            </div>
                        </fieldset>
                    }
                </div>
            </div>
        </div>
    </div>
</div>