RentACar/Models/Vozilo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RentACar.Models
{
    public class Vozilo
    {
        public Guid ID { get; set; }
        public string RegistarskiBroj { get; set; }
        public string Boja { get; set; }
        public int BrojOsoba { get; set; }
        public bool Automatik { get; set; }
        public string TipGoriva { get; set; }
        public string TipVozila { get; set; }
        public string Slika { get; set; }
        public decimal CijenaPoDanu { get; set; }
        public int GodinaProizvodnje { get; set; }
        public Guid FilijalaID { get; set; }
        public Guid ModelVozilaID { get; set; }
    }
}

RentACar/Controllers/VoziloController.cs
using RentACar.App_Start;
using RentACar.BLL;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RentACar.Controllers
{
    public class VoziloController : Controller
    {
        private VoziloServis voziloServis;

        public VoziloController()
        {
            this.voziloServis = new VoziloServis();
        }

        /// <summary>
        /// Prikazuje vozila, proizvođače i modele vozila.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Prikazuje listu vozila.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        public ActionResult ListaVozila()
        {
            var vozila = voziloServis.DohvatiVozila();
            return View(vozila);
        }

        /// <summary>
        /// Prikazuje formu za unos novog vozila.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult KreirajVozilo()
        {
            var modeliVozila = voziloServis.DohvatiModeleVozila();
            var filijale = voziloServis.DohvatiFilijale();
            ViewBag.ModeliVozila = modeliVozila.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        });

            ViewBag.Filijale = filijale.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 
            return View();
        }

        /// <summary>
        /// Kreira novo vozilo.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult KreirajVozilo(Vozilo model)
        {
            if (ModelState.IsValid)
            {
                var vozilo = new DAL.Vozilo
                {
                    Boja = model.Boja,
                    RegistarskiBroj = model.RegistarskiBroj.ToUpper(),
                    CijenaPoDanu = model.CijenaPoDanu,
                    GodinaProizvodnje = model.GodinaProizvodnje,
                    FilijalaID = model.FilijalaID,
                    ModelVozilaID = model.ModelVozilaID,
                    Slika = model.Slika,
                    ID = Guid.NewGuid()
                };
                if (voziloServis.DohvatiVoziloPoRegistraciji(vozilo.RegistarskiBroj) != null)
                {
                    ModelState.AddModelError("", "Vozilo sa registarskim brojem " + vozilo.RegistarskiBroj + " već postoji.");
                } 
                else
                {
                    voziloServis.Sacuvaj(vozilo);
                    return RedirectToAction("Index");
                }
            }

            var modeliVozila = voziloServis.DohvatiModeleVozila();
            var filijale = voziloServis.DohvatiFilijale();
            ViewBag.ModeliVozila = modeliVozila.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        });

            ViewBag.Filijale = filijale.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 

            return View(model);
        }

        /// <summary>
        /// Prikazuje detalje traženog vozila.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpGet]
        public JsonResult DetaljiVozila(Guid ID)
        {
            var vozilo = voziloServis.DohvatiVozilo(ID);

            var model = new Vozilo
            {
                Boja = vozilo.Boja,
                CijenaPoDanu = vozilo.CijenaPoDanu,
                GodinaProizvodnje = vozilo.GodinaProizvodnje,
                BrojOsoba = vozilo.ModelVozila.BrojOsoba,
                TipGoriva = vozilo.ModelVozila.TipGoriva.Naziv,
                TipVozila = vozilo.ModelVozila.TipVozila.Naziv,
                Automatik = vozilo.ModelVozila.Automatik,
                ID = vozilo.ID,
                RegistarskiBroj = vozilo.RegistarskiBroj,
                Slika = vozilo.Slika
            };

            return Json(model, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg vozila.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult UrediVozilo(Guid ID)
        {
            var modeliVozila = voziloServis.DohvatiModeleVozila();
            var filijale = voziloServis.DohvatiFilijale();
            ViewBag.ModeliVozila = modeliVozila.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        });

            ViewBag.Filijale = filijale.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 

            var vozilo = voziloServis.DohvatiVozilo(ID);
            var model = new Vozilo
            {
                Boja = vozilo.Boja,
                CijenaPoDanu = vozilo.CijenaPoDanu,
                FilijalaID = vozilo.FilijalaID,
                GodinaProizvodnje = vozilo.GodinaProizvodnje,
                ModelVozilaID = vozilo.ModelVozilaID,
                RegistarskiBroj = vozilo.RegistarskiBroj,
                Slika = vozilo.Slika,
                ID = vozilo.ID
            };
            return View(model);
        }

        /// <summary>
        /// Ažurira postojeće vozilo.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult UrediVozilo(Vozilo model)
        {
            if (ModelState.IsValid)
            {
                if (voziloServis.DohvatiVozilo(model.ID).Slika != null && model.Slika != null)
                    ObrisiSliku(voziloServis.DohvatiVozilo(model.ID).Slika);

                var vozilo = new DAL.Vozilo
                {
                    Boja = model.Boja,
                    RegistarskiBroj = model.RegistarskiBroj.ToUpper(),
                    CijenaPoDanu = model.CijenaPoDanu,
                    GodinaProizvodnje = model.GodinaProizvodnje,
                    FilijalaID = model.FilijalaID,
                    ModelVozilaID = model.ModelVozilaID,
                    Slika = model.Slika,
                    ID = model.ID
                };

                voziloServis.Azuriraj(vozilo);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Briše vozilo prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        public JsonResult ObrisiVozilo(Guid ID)
        {
            var vozilo = voziloServis.DohvatiVozilo(ID);

            voziloServis.Obrisi(vozilo);

            if (vozilo.Slika != null)
                ObrisiSliku(vozilo.Slika);

            return Json("OK");
        }

        /// <summary>
        /// Čuva sliku za traženo vozilo.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public JsonResult SacuvajSliku()
        {
            for (int i = 0; i < Request.Files.Count; i++)
            {
                var file = Request.Files[i];

                var fileName = Path.GetFileName(file.FileName);
                var path = "/Slike/Vozila/" + fileName;
                var fullPath = Server.MapPath(path);
                file.SaveAs(fullPath);

                return Json(path, JsonRequestBehavior.AllowGet);
            }
            return Json("ERROR");
        }

        /// <summary>
        /// Briše sliku za traženo vozilo.
        /// </summary>
        /// <param name="Slika"></param>
        [Autorizacija]
        [HttpPost]
        public void ObrisiSliku(string Slika)
        {
            string fullPath = Request.MapPath(Slika);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
            }
        }

        /// <summary>
        /// Lista najčešće iznajmljivanih vozila.
        /// </summary>
        /// <param name="Broj"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public JsonResult TopVozila(int Broj)
        {
            var vozila = voziloServis.DohvatiTopVozila(Broj);
            return Json(vozila, JsonRequestBehavior.AllowGet);
        }
    }
}

RentACar/Views/Vozilo/Index.cshtml
<script type="text/javascript">
    $(document).ready(function () {
        $('#lista-vozila').load('/Vozilo/ListaVozila');

        $('#prikazi-vozila').click(function () {
            $('#prikazi-vozila').addClass('active');
            $('#prikazi-modele-vozila').removeClass('active');
            $('#prikazi-proizvodjace').removeClass('active');

            $('#lista-modela-vozila').addClass('hidden');
            $('#lista-proizvodjaca').addClass('hidden');
            $('#lista-vozila').removeClass('hidden');

            $('#lista-vozila').load('/Vozilo/ListaVozila');
        });

        $('#prikazi-modele-vozila').click(function () {
            $('#prikazi-vozila').removeClass('active');
            $('#prikazi-modele-vozila').addClass('active');
            $('#prikazi-proizvodjace').removeClass('active');

            $('#lista-modela-vozila').removeClass('hidden');
            $('#lista-proizvodjaca').addClass('hidden');
            $('#lista-vozila').addClass('hidden');

            $('#lista-modela-vozila').load('/ModelVozila/Index');
        });

        $('#prikazi-proizvodjace').click(function () {
            $('#prikazi-vozila').removeClass('active');
            $('#prikazi-modele-vozila').removeClass('active');
            $('#prikazi-proizvodjace').addClass('active');

            $('#lista-modela-vozila').addClass('hidden');
            $('#lista-proizvodjaca').removeClass('hidden');
            $('#lista-vozila').addClass('hidden');

            $('#lista-proizvodjaca').load('/Proizvodjac/Index');
        });
    });
</script>

<ul class="nav nav-tabs margin-top-20">
    <li class="active" id="prikazi-vozila"><a href="#">Vozila</a></li>
    <li id="prikazi-modele-vozila"><a href="#">Modeli</a></li>
    <li id="prikazi-proizvodjace"><a href="#">Proizvođači</a></li>
</ul>

<div class="hidden" id="lista-modela-vozila"></div>

<div class="hidden" id="lista-proizvodjaca"></div>

<div id="lista-vozila"></div>

RentACar/Views/Vozilo/KreirajVozilo.cshtml
@model RentACar.Models.Vozilo
@{
    ViewBag.Title = "Novo vozilo";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<script src="~/Scripts/jQuery-File-Upload-9.11.0/js/vendor/jquery.ui.widget.js"></script>
<script src="~/Scripts/jQuery-File-Upload-9.11.0/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jQuery-File-Upload-9.11.0/js/jquery.fileupload.js"></script>
<script src="~/Scripts/spectrum.js"></script>
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Scripts/spectrum.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {

        PorukeValidacija();

        $("#forma-vozilo").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                GodinaProizvodnje: {
                    required: true,
                    min: 1990,
                    number: true
                },
                CijenaPoDanu: {
                    required: true,
                    max: 1000000,
                    number: true
                },
                RegistarskiBroj: {
                    required: true,
                    minlength: 7,
                    maxlength: 7
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });

        $('#FilijalaLista').select2({ placeholder: "Izaberite filijalu..." });
        $('#ModelVozilaLista').select2({ placeholder: "Izaberite model vozila..." });

        $('#Boja').spectrum({ color: "#f00", preferredFormat: "hex" });
        $('#Boja').val("#f00");

        $("#FileUpload").on('change', function () {
            $('#Slika').val("/Slike/Vozila/" + document.getElementById("FileUpload").files[0].name);
        });
        
        $("#sacuvaj-vozilo").on("click", function () {
            var formData = new FormData();
            var totalFiles = document.getElementById("FileUpload").files.length;
            for (var i = 0; i < totalFiles; i++) {
                var file = document.getElementById("FileUpload").files[i];

                formData.append("FileUpload", file);
            }
            $.ajax({
                type: "POST",
                url: '/Vozilo/SacuvajSliku',
                data: formData,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (rezultat) {
                    if (rezultat != "ERROR"){
                        $('#Slika').val(rezultat);
                    }
                        
                },
                error: function (error) {
                    alert("error");
                }
            });
        });
    });
</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("KreirajVozilo", "Vozilo", FormMethod.Post, new { @id = "forma-vozilo" }))
        {
            <span class="error">@Html.ValidationSummary(true, "Čuvanje vozila nije uspjelo.");</span>
            <div>
                <fieldset>
                    <legend>Detalji vozila</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Registarski broj</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.RegistarskiBroj, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.RegistarskiBroj, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Boja</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Boja, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Boja, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Godina proizvodnje</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.GodinaProizvodnje, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.GodinaProizvodnje, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Model vozila</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.ModelVozilaID, (IEnumerable<SelectListItem>)ViewBag.ModeliVozila, new { @id = "ModelVozilaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.ModelVozilaID, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Filijala</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.FilijalaID, (IEnumerable<SelectListItem>)ViewBag.Filijale, new { @id = "FilijalaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.FilijalaID, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Cijena po danu</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.CijenaPoDanu, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.CijenaPoDanu, null, new { @class = "inline-help error"})
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Slika vozila</label>
                            @Html.TextBoxFor(u => u.Slika, new { @class = "form-control", @type = "text", @readonly="" }) &nbsp;
                            <input type="file" id="FileUpload" multiple />
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" id="sacuvaj-vozilo" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Vozilo", null, new { @class = "btn btn-default", @id = "odustani" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

RentACar/Views/Vozilo/ListaVozila.cshtml
@model IEnumerable<RentACar.DAL.Vozilo>
@{
    ViewBag.Title = "Vozila";
    Layout = null;
}

<script type="text/javascript">
    $(document).ready(function () {
        $(".obrisi-vozilo").click(function (e) {
            e.preventDefault();
            var voziloID = $(this).closest("tr")
                                   .find(".vozilo-id")
                                   .text();

            var voziloRegistracija = $(this).closest("tr")
                                   .find(".vozilo-naziv")
                                   .text();

            var potvrdaBrisanja = confirm("Da li ste sigurni da želite da obrišete vozilo " + voziloRegistracija + " ?");
            if (potvrdaBrisanja == true) {
                $.ajax({
                    type: "POST",
                    url: "/Vozilo/ObrisiVozilo",
                    data: "ID=" + voziloID,
                    success: function (rezultat) {
                        if (rezultat == "OK") {
                            alert("Vozilo" + voziloRegistracija + " je uspješno obrisano.");
                            location.reload();
                        }
                        else {
                            alert("Došlo je do greške prilikom brisanja vozila " + voziloRegistracija);
                        }

                    }
                });
            }
        });
    });
</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>
<div class="panel-kontrole clearfix">
    <a class="btn btn-success" href="@Url.Action("KreirajVozilo", "Vozilo")"><i class="glyphicon glyphicon-plus"></i> Novo vozilo</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th></th>
                    <th>Registarski broj</th>
                    <th>Boja</th>
                    <th>Model</th>
                    <th>Godina proizvodnje</th>
                    <th>Proizvođač</th>
                    <th>Cijena po danu</th>
                    <th>Filijala</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="filijala-tabela">
                @foreach (var vozilo in Model)
                {
                    <tr>
                        <td class="hidden vozilo-id">@vozilo.ID</td>
                        <td><img src="@vozilo.Slika" alt="@vozilo.ModelVozila.Naziv" width="150" class="topvozila-slika" /></td>
                        <td class="vozilo-registracija">@vozilo.RegistarskiBroj</td>
                        <td><span style="background-color: @vozilo.Boja;" class="vozilo-boja"></span></td>
                        <td>@vozilo.ModelVozila.Naziv</td>
                        <td>@vozilo.GodinaProizvodnje</td>
                        <td>@vozilo.ModelVozila.Proizvodjac.Naziv</td>
                        <td>@vozilo.CijenaPoDanu</td>
                        <td>@vozilo.Filijala.Naziv</td>
                        <td>
                            <a class="btn btn-default" href="@Url.Action("UrediVozilo", "Vozilo", new { ID = vozilo.ID })"><i class="glyphicon glyphicon-edit"></i> Uredi</a>
                            <a class="btn btn-danger obrisi-vozilo" href="#"><i class="glyphicon glyphicon-remove"></i> Obriši</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RentACar/Views/Vozilo/UrediVozilo.cshtml
@model RentACar.Models.Vozilo
@{
    ViewBag.Title = "Uredi vozilo";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />

<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<script src="~/Scripts/jQuery-File-Upload-9.11.0/js/vendor/jquery.ui.widget.js"></script>
<script src="~/Scripts/jQuery-File-Upload-9.11.0/js/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jQuery-File-Upload-9.11.0/js/jquery.fileupload.js"></script>
<script src="~/Scripts/spectrum.js"></script>
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<link href="~/Content/select2.min.css" rel="stylesheet" />
<link href="~/Scripts/spectrum.css" rel="stylesheet" />

<script type="text/javascript">
    $(document).ready(function () {

        PorukeValidacija();

        $("#forma-vozilo").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                GodinaProizvodnje: {
                    required: true,
                    min: 1990,
                    number: true
                },
                CijenaPoDanu: {
                    required: true,
                    max: 1000000,
                    number: true
                },
                RegistarskiBroj: {
                    required: true,
                    minlength: 7,
                    maxlength: 7
                },
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });

        $('#FilijalaLista').select2({ placeholder: "Izaberite filijalu..." });
        $('#ModelVozilaLista').select2({ placeholder: "Izaberite model vozila..." });

        $('#Boja').spectrum({ preferredFormat: "hex" });

        $("#FileUpload").on('change', function () {
            $('#Slika').val("/Slike/Vozila/" + document.getElementById("FileUpload").files[0].name);
        });

        $("#sacuvaj-vozilo").on("click", function () {
            var formData = new FormData();
            var totalFiles = document.getElementById("FileUpload").files.length;
            for (var i = 0; i < totalFiles; i++) {
                var file = document.getElementById("FileUpload").files[i];

                formData.append("FileUpload", file);
            }
            $.ajax({
                type: "POST",
                url: '/Vozilo/SacuvajSliku',
                data: formData,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (rezultat) {
                    if (rezultat != "ERROR") {
                        $('#Slika').val(rezultat);
                    }

                },
                error: function (error) {
                    alert("error");
                }
            });
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("UrediVozilo", "Vozilo", FormMethod.Post, new { @id = "forma-vozilo" }))
        {
            @Html.ValidationSummary(true, "Čuvanje vozila nije uspjelo.");
            <div>
                <fieldset>
                    <legend>Detalji vozila</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Registarski broj</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.RegistarskiBroj, new { @class = "form-control", @readonly = "" })
                                @Html.ValidationMessageFor(u => u.RegistarskiBroj, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Boja</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Boja, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Boja, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Godina proizvodnje</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.GodinaProizvodnje, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.GodinaProizvodnje, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Model vozila</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.ModelVozilaID, (IEnumerable<SelectListItem>)ViewBag.ModeliVozila, new { @id = "ModelVozilaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.ModelVozilaID, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Filijala</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.FilijalaID, (IEnumerable<SelectListItem>)ViewBag.Filijale, new { @id = "FilijalaLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.FilijalaID, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Cijena po danu</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.CijenaPoDanu, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.CijenaPoDanu, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Slika vozila</label>
                            @Html.TextBoxFor(u => u.Slika, new { @class = "form-control", @type = "text", @readonly = "" }) &nbsp;
                            <input type="file" id="FileUpload" multiple />
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" id="sacuvaj-vozilo" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Vozilo", null, new { @class = "btn btn-default", @id="odustani" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>