RentACar/Models/Grad.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RentACar.Models
{
    public class Grad
    {
        public Guid ID { get; set; }
        public string Naziv { get; set; }
        public string PozivniBroj { get; set; }
    }
}

RentACar/Controllers/GradController.cs
using RentACar.App_Start;
using RentACar.BLL;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RentACar.Controllers
{
    public class GradController : Controller
    {
        private GradServis gradServis;

        public GradController()
        {
            this.gradServis = new GradServis();
        }

        /// <summary>
        /// Prikazuje listu gradova.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        public ActionResult Index()
        {
            var gradovi = gradServis.DohvatiGradove();
            return View(gradovi);
        }

        /// <summary>
        /// Prikazuje formu za kreiranje novog grada.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult KreirajGrad()
        {
            return View();
        }

        /// <summary>
        /// Kreira novi grad.
        /// </summary>
        /// <param name="isModal"></param>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult KreirajGrad(bool? isModal, Grad model)
        {
            if (ModelState.IsValid)
            {
                var grad = new DAL.Grad
                {
                    Naziv = model.Naziv,
                    PozivniBroj = model.PozivniBroj,
                    ID = Guid.NewGuid()
                };

                if(gradServis.DohvatiGradPoNazivu(grad.Naziv) != null)
                {
                    ModelState.AddModelError("", "Unešeni grad već postoji.");
                    return View(model);
                }
                else
                {
                    gradServis.Sacuvaj(grad);
                    if (isModal.HasValue)
                        return Json("OK");
                    else
                        return RedirectToAction("Index");
                }
                
            }
            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje postojećeg grada.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult UrediGrad(Guid ID)
        {
            var proizvodjac = gradServis.DohvatiGrad(ID);
            var model = new Grad
            {
                Naziv = proizvodjac.Naziv,
                PozivniBroj = proizvodjac.PozivniBroj,
                ID = proizvodjac.ID
            };
            return View(model);
        }

        /// <summary>
        /// Ažurira postojeći grad.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult UrediGrad(Grad model)
        {
            if (ModelState.IsValid)
            {
                var grad = new DAL.Grad
                {
                    PozivniBroj = model.PozivniBroj,
                    ID = model.ID
                };

                gradServis.Azuriraj(grad);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Briše grad prema ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        public JsonResult ObrisiGrad(Guid ID)
        {
            var grad = gradServis.DohvatiGrad(ID);
            gradServis.Obrisi(grad);

            return Json("OK");
        }
    }
}

RentACar/Views/Grad/Index.cshtml
@model IEnumerable<RentACar.DAL.Grad>
@{
    ViewBag.Title = "Gradovi";
}

<script type="text/javascript">
    $(document).ready(function () {

        $(".obrisi-grad").click(function (e) {
            e.preventDefault();
            var gradID = $(this).closest("tr")
                                   .find(".grad-id")
                                   .text();
            var potvrdaBrisanja = confirm("Da li ste sigurni da želite da obrišete grad?");
            if (potvrdaBrisanja == true) {
                $.ajax({
                    type: "POST",
                    url: "/Grad/ObrisiGrad",
                    data: "ID=" + gradID,
                    success: function (rezultat) {
                        if (rezultat == "OK") {
                            alert("Grad je uspješno izbrisan.");
                            location.reload();
                        }
                        else {
                            alert("Došlo je do greške prilikom brisanja grada.");
                        }

                    }
                });
            }
        });
    });
</script>



<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="panel-kontrole clearfix">
    <a class="btn btn-success" href="@Url.Action("KreirajGrad", "Grad")"><i class="glyphicon glyphicon-plus"></i> Novi grad</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>Naziv</th>
                    <th>Pozivni broj</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var grad in Model)
                {
                    <tr>
                        <td class="hidden grad-id">@grad.ID</td>
                        <td>@grad.Naziv</td>
                        <td>@grad.PozivniBroj</td>
                        <td><a class="btn btn-default" href="@Url.Action("UrediGrad", "Grad", new { ID = grad.ID })"><i class="glyphicon glyphicon-edit"></i> Uredi</a>
                            <a class="btn btn-danger obrisi-grad" href="#"><i class="glyphicon glyphicon-remove"></i> Obriši</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RentACar/Views/Grad/KreirajGrad.cshtml
@model RentACar.Models.Grad
@{
    ViewBag.Title = "Novi grad";
}
<script type="text/javascript" src="~/Scripts/helpers.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#forma-grad").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                Adresa: {
                    required: true,
                    minlength: 2
                },
                BrojTelefona: {
                    required: true,
                    minlength: 6,
                    maxlength: 7
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("KreirajGrad", "Grad", FormMethod.Post, new { @id = "forma-grad" }))
        {
            @Html.ValidationSummary(true, "Čuvanje grada nije uspjelo.");
            <div>
                <fieldset>
                    <legend>Detalji grada</legend>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Naziv</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Naziv, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Naziv, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Pozivni broj</label>
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(u => u.PozivniBroj, new { @class = "form-control", @type="number" })
                            @Html.ValidationMessageFor(u => u.PozivniBroj, null, new { @class = "inline-help error" })
                        </div>
                    </div>
                        
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Grad", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

RentACar/Views/Grad/UrediGrad.cshtml
@model RentACar.Models.Grad
@{
    ViewBag.Title = "Uredi grad";
}

<script type="text/javascript" src="~/Scripts/helpers.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        PorukeValidacija();
        $("#forma-grad").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                PozivniBroj: {
                    required: true,
                    minlength: 3,
                    maxlength: 3
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });
</script>


<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("UrediGrad", "Grad", FormMethod.Post, new { @id = "forma-grad" }))
        {
            @Html.ValidationSummary(true, "Čuvanje grada nije uspjelo.");
            <div>
                <fieldset>
                    <legend>Detalji grada</legend>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Naziv</label>
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(u => u.Naziv, new { @class = "form-control", @readonly = "" })
                            @Html.ValidationMessageFor(u => u.Naziv, null, new { @class = "inline-help error" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Pozivni broj</label>
                        </div>
                        <div class="editor-field">
                            @Html.TextBoxFor(u => u.PozivniBroj, new { @class = "form-control", @type = "number" })
                            @Html.ValidationMessageFor(u => u.PozivniBroj, null, new { @class = "inline-help error" })
                        </div>
                    </div>

                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Grad", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>