RentACar/Models/Filijala.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RentACar.Models
{
    public class Filijala
    {
        public Guid ID { get; set; }
        public string Naziv { get; set; }
        public string Adresa { get; set; }
        public Guid GradID { get; set; }
        public string BrojTelefona { get; set; }
    }
}

RentACar/Controllers/FilijalaController.cs
using RentACar.App_Start;
using RentACar.BLL;
using RentACar.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace RentACar.Controllers
{
    public class FilijalaController : Controller
    {
        private FilijalaServis filijalaServis;

        public FilijalaController()
        {
            this.filijalaServis = new FilijalaServis();
        }

        /// <summary>
        /// Prikazuje listu filijala.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        public ActionResult Index()
        {
            var filijale = filijalaServis.DohvatiFilijale();
            return View(filijale);
        }

        /// <summary>
        /// Prikazuje formu za unos nove filijale.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult KreirajFilijalu()
        {
            var gradovi = filijalaServis.DohvatiGradove();
            ViewBag.Gradovi = gradovi.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 
            return View();
        }

        /// <summary>
        /// Kreira novu filijalu.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult KreirajFilijalu(Filijala model)
        {
            if (ModelState.IsValid)
            {
                var filijala = new DAL.Filijala
                {
                    Adresa = model.Adresa,
                    BrojTelefona = model.BrojTelefona,
                    GradID = model.GradID,
                    Naziv = model.Naziv,
                    ID = Guid.NewGuid()
                };

                var postojecaFilijala = filijalaServis.DohvatiFilijaluPoNazivu(filijala.Naziv);

                if(postojecaFilijala != null)
                {
                    ModelState.AddModelError("", "Filijala sa unešenim nazivom već postoji.");
                }
                else
                {
                    filijalaServis.Sacuvaj(filijala);
                    return RedirectToAction("Index");
                }
            }

            var gradovi = filijalaServis.DohvatiGradove();
            ViewBag.Gradovi = gradovi.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 

            return View(model);
        }

        /// <summary>
        /// Prikazuje formu za ažuriranje filijale.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public ActionResult UrediFilijalu(Guid ID)
        {
            var gradovi = filijalaServis.DohvatiGradove();
            ViewBag.Gradovi = gradovi.Select(x =>
                        new SelectListItem
                        {
                            Value = x.ID.ToString(),
                            Text = x.Naziv
                        }); 

            var filijala = filijalaServis.DohvatiFilijalu(ID);
            var model = new Filijala
            {
                Adresa = filijala.Adresa,
                GradID = filijala.GradID,
                Naziv = filijala.Naziv,
                BrojTelefona = filijala.BrojTelefona,
                ID = filijala.ID
            };
            return View(model);
        }

        /// <summary>
        /// Ažurira postojeću filijalu.
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpPost]
        public ActionResult UrediFilijalu(Filijala model)
        {
            if (ModelState.IsValid)
            {
                var filijala = new DAL.Filijala
                {
                    Adresa = model.Adresa,
                    GradID = model.GradID,
                    BrojTelefona = model.BrojTelefona,
                    ID = model.ID
                };

                filijalaServis.Azuriraj(filijala);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        /// <summary>
        /// Briše filijalu prema njenom ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        public JsonResult ObrisiFilijalu(Guid ID)
        {
            var filijala = filijalaServis.DohvatiFilijalu(ID);
            filijalaServis.Obrisi(filijala);

            return Json("OK");
        }

        /// <summary>
        /// Prikazuje grad prema njegovom ID-u.
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public JsonResult DohvatiGrad(Guid ID)
        {
            var model = filijalaServis.DohvatiGrad(ID);
            var grad = new Grad
            {
                ID = model.ID,
                Naziv = model.Naziv,
                PozivniBroj = model.PozivniBroj
            };

            return Json(grad, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Prikazuje promet prema filijalama.
        /// </summary>
        /// <returns></returns>
        [Autorizacija]
        [HttpGet]
        public JsonResult PrometPoFilijalama()
        {
            var filijale = filijalaServis.DohvatiPrometPoFilijalama();
            return Json(filijale, JsonRequestBehavior.AllowGet);
        }
    }
}

RentACar/Views/Filijala/Index.cshtml
@model IEnumerable<RentACar.DAL.Filijala>
@{
    ViewBag.Title = "Filijale";
}

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $(".obrisi-filijalu").click(function (e) {
            e.preventDefault();
            var filijalaID = $(this).closest("tr")
                                   .find(".filijala-id")     
                                   .text();

            var filijalaNaziv = $(this).closest("tr")
                                   .find(".filijala-naziv")
                                   .text();

            var potvrdaBrisanja = confirm("Da li ste sigurni da želite da obrišete filijalu " + filijalaNaziv + " ?");
            if (potvrdaBrisanja == true) {
                $.ajax({
                    type: "POST",
                    url: "/Filijala/ObrisiFilijalu",
                    data: "ID=" + filijalaID,
                    success: function (rezultat) {
                        if (rezultat == "OK") {
                            alert(filijalaNaziv + " je uspješno obrisana");
                            location.reload();
                        }
                        else {
                            alert("Došlo je do greške prilikom brisanja filijale " + filijalaNaziv);
                        }
                        
                    }
                });
            }
        });
    });
</script>

<div class="panel-kontrole clearfix">
    <a class="btn btn-success" href="@Url.Action("KreirajFilijalu", "Filijala")"><i class="glyphicon glyphicon-plus"></i> Nova filijala</a>
</div>

<div class="row">
    <div class="col-md-12">
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th>Naziv</th>
                    <th>Adresa</th>
                    <th>Grad</th>
                    <th>Broj telefona</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="filijala-tabela">
                @foreach (var filijala in Model)
                {
                    <tr>
                        <td class="hidden filijala-id">@filijala.ID</td>
                        <td class="filijala-naziv">@filijala.Naziv</td>
                        <td>@filijala.Adresa</td>
                        <td>@filijala.Grad.Naziv</td>
                        <td>@filijala.Grad.PozivniBroj @filijala.BrojTelefona</td>
                        <td>
                            <a class="btn btn-default" href="@Url.Action("UrediFilijalu", "Filijala", new { ID = filijala.ID })"><i class="glyphicon glyphicon-edit"></i> Uredi</a>
                            <a class="btn btn-danger obrisi-filijalu" href="#"><i class="glyphicon glyphicon-remove"></i> Obriši</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

RentACar/Views/Filijala/KreirajFilijalu.cshtml
@model RentACar.Models.Filijala
@{
    ViewBag.Title = "Nova filijala";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        PorukeValidacija();

        $('#GradLista').select2({ placeholder: "Izaberite grad..." });

        $.ajax({
            type: "GET",
            url: "/Filijala/DohvatiGrad",
            data: "ID=" + $("#GradLista").val(),
            contentType: 'application/json; charset=utf-8',
            success: function (rezultat) {
                if (rezultat != null) {
                    $('#pozivni-za-grad').text(rezultat.PozivniBroj);
                }

            }
        });

        $('#GradLista').select2().on("change", function () {
            $.ajax({
                type: "GET",
                url: "/Filijala/DohvatiGrad",
                data: "ID=" + $("#GradLista").val(),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat != null) {
                        $('#pozivni-za-grad').text(rezultat.PozivniBroj);
                    }

                }
            });
        });

        $('#novi-grad').click(function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "/Grad/KreirajGrad",
                data: JSON.stringify({
                    isModal: true,
                    Naziv: $('#grad-naziv').val(),
                    PozivniBroj: $('#grad-pozivniBroj').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja grada.");
                    }

                }
            });
        });

        $("#forma-filijala").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                Adresa: {
                    required: true,
                    minlength: 2
                },
                BrojTelefona: {
                    required: true,
                    minlength: 6,
                    maxlength: 7,
                    digits: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("KreirajFilijalu", "Filijala", FormMethod.Post, new { @id = "forma-filijala" }))
        {
            <span class="error">@Html.ValidationSummary(true, "Čuvanje filijale nije uspjelo.")</span>
            <div>
                <fieldset>
                    <legend>Detalji filijale</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Naziv</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Naziv, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Naziv, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Adresa</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Adresa, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Adresa, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Grad</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.GradID, (IEnumerable<SelectListItem>)ViewBag.Gradovi, new { @id = "GradLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.GradID, null, new { @class = "inline-help error" })
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#grad-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj grad
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj telefona</label>
                            </div>
                            <div class="editor-field">
                                <i class="glyphicon glyphicon-phone"></i> <span id="pozivni-za-grad"></span>
                                @Html.TextBoxFor(u => u.BrojTelefona, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(u => u.BrojTelefona, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Filijala", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal grada*@
<div class="modal fade" id="grad-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi grad</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviGrad" id="forma-grada">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Naziv</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Naziv" id="grad-naziv" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Pozivni broj</label>
                        </div>
                        <div class="editor-field">
                            <input type="number" name="PozivniBroj" id="grad-pozivniBroj" class="form-control" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="novi-grad" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

RentACar/Views/Filijala/UrediFilijalu.cshtml
@model RentACar.Models.Filijala
@{
    ViewBag.Title = "Uredi filijalu";
}
<script type="text/javascript" src="~/Scripts/select2.min.js"></script>
<link href="~/Content/select2.min.css" rel="stylesheet" />
<script type="text/javascript" src="~/Scripts/helpers.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
       PorukeValidacija();

        $('#GradLista').select2({ placeholder: "Izaberite grad..." });

        $.ajax({
            type: "GET",
            url: "/Filijala/DohvatiGrad",
            data: "ID=" + $("#GradLista").val(),
            contentType: 'application/json; charset=utf-8',
            success: function (rezultat) {
                if (rezultat != null) {
                    $('#pozivni-za-grad').text(rezultat.PozivniBroj);
                }

            }
        });

        $('#GradLista').select2().on("change", function () {
            $.ajax({
                type: "GET",
                url: "/Filijala/DohvatiGrad",
                data: "ID=" + $("#GradLista").val(),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat != null) {
                        $('#pozivni-za-grad').text(rezultat.PozivniBroj);
                    }

                }
            });
        });

        $('#novi-grad').click(function (e) {
            e.preventDefault();

            $.ajax({
                type: "POST",
                url: "/Grad/KreirajGrad",
                data: JSON.stringify({
                    isModal: true,
                    Naziv: $('#grad-naziv').val(),
                    PozivniBroj: $('#grad-pozivniBroj').val()
                }),
                contentType: 'application/json; charset=utf-8',
                success: function (rezultat) {
                    if (rezultat == "OK") {
                        location.reload();
                    }
                    else {
                        alert("Došlo je do greške prilikom čuvanja grada.");
                    }

                }
            });
        });

        $("#forma-filijala").validate({
            rules: {
                Naziv: {
                    required: true,
                    minlength: 2
                },
                Adresa: {
                    required: true,
                    minlength: 2
                },
                BrojTelefona: {
                    required: true,
                    minlength: 6,
                    maxlength: 7,
                    digits: true
                }
            },
            highlight: function (element) {
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function (element) {
                $(element).closest('.form-group').removeClass('has-error');
            }
        });
    });

</script>

<div class="page-header">
    <h1>@ViewBag.Title</h1>
</div>

<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("UrediFilijalu", "Filijala", FormMethod.Post, new { @id = "forma-filijala" }))
        {
            @Html.ValidationSummary(true, "Čuvanje filijale nije uspjelo.");
            <div>
                <fieldset>
                    <legend>Detalji filijale</legend>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Naziv</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Naziv, new { @class = "form-control", @readonly = "" })
                                @Html.ValidationMessageFor(u => u.Naziv, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Adresa</label>
                            </div>
                            <div class="editor-field">
                                @Html.TextBoxFor(u => u.Adresa, new { @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.Adresa, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Grad</label>
                            </div>
                            <div class="editor-field">
                                @Html.DropDownListFor(u => u.GradID, (IEnumerable<SelectListItem>)ViewBag.Gradovi, new { @id = "GradLista", @class = "form-control" })
                                @Html.ValidationMessageFor(u => u.GradID, null, new { @class = "inline-help error" })
                                <!-- Aktiviraj proizvođači modal -->
                                <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#grad-modal">
                                    <i class="glyphicon glyphicon-plus"></i> Dodaj grad
                                </button>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="editor-label">
                                <label>Broj telefona</label>
                            </div>
                            <div class="editor-field">
                                <i class="glyphicon glyphicon-phone"></i> <span id="pozivni-za-grad"></span>
                                @Html.TextBoxFor(u => u.BrojTelefona, new { @class = "form-control", @type = "number" })
                                @Html.ValidationMessageFor(u => u.BrojTelefona, null, new { @class = "inline-help error" })
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input class="btn btn-primary" type="submit" value="Sačuvaj" />
                        @Html.ActionLink("Odustani", "Index", "Filijala", null, new { @class = "btn btn-default" })
                    </div>
                </fieldset>
            </div>
        }
    </div>
</div>

@*Modal grada*@
<div class="modal fade" id="grad-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Novi grad</h4>
            </div>
            <div class="modal-body">
                <form method="post" name="NoviGrad" id="forma-grada">
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Naziv</label>
                        </div>
                        <div class="editor-field">
                            <input type="text" name="Naziv" id="grad-naziv" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="editor-label">
                            <label>Pozivni broj</label>
                        </div>
                        <div class="editor-field">
                            <input type="number" name="PozivniBroj" id="grad-pozivniBroj" class="form-control" />
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="novi-grad" class="btn btn-primary">Save changes</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->